CREATE TABLE GATEWAY_USER ( 
   id BIGINT NOT NULL PRIMARY KEY, 
   first_name VARCHAR2(50) NOT NULL, 
   last_name VARCHAR2(50) NOT NULL
);

CREATE TABLE SYSTEM ( 
   id BIGINT NOT NULL PRIMARY KEY, 
   name VARCHAR2(500) NOT NULL,
   url VARCHAR2(500) NOT NULL
);

CREATE TABLE SYSTEM_FIELD ( 
   id BIGINT NOT NULL PRIMARY KEY,
   system_id BIGINT NOT NULL,
   field_name VARCHAR2(50) NOT NULL,
   FOREIGN KEY (system_id) REFERENCES SYSTEM(id)
);

CREATE TABLE GATEWAY_USER_SYSTEM_FIELD_VALUE ( 
   id BIGINT NOT NULL PRIMARY KEY,
   user_system_field_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL,
   field_value VARCHAR2(50) NOT NULL,
   FOREIGN KEY (user_system_field_id) REFERENCES SYSTEM_FIELD(id),
   FOREIGN KEY (user_id) REFERENCES GATEWAY_USER(id)
);

CREATE SEQUENCE "GATEWAY_USER_SEQ" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1;

CREATE SEQUENCE "SYSTEM_SEQ"
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1;

CREATE SEQUENCE "SYSTEM_FIELD_SEQ"
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1;

CREATE SEQUENCE "GATEWAY_USER_SYSTEM_FIELD_VALUE_SEQ"
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1;