CREATE TABLE GATEWAY_USER ( 
   id INT NOT NULL PRIMARY KEY, 
   first_name VARCHAR(50) NOT NULL, 
   last_name VARCHAR(50) NOT NULL
);

CREATE TABLE SYSTEM ( 
   id INT NOT NULL PRIMARY KEY, 
   name VARCHAR(500) NOT NULL,
   url VARCHAR(500) NOT NULL
);

CREATE TABLE SYSTEM_FIELD ( 
   id INT NOT NULL PRIMARY KEY,
   system_id INT NOT NULL,
   field_name VARCHAR(50) NOT NULL,
   FOREIGN KEY (system_id) REFERENCES SYSTEM(id)
);

CREATE TABLE GATEWAY_USER_SYSTEM_FIELD_VALUE ( 
   id INT NOT NULL PRIMARY KEY,
   user_system_field_id INT NOT NULL,
   user_id INT NOT NULL,
   field_value VARCHAR(50) NOT NULL,
   FOREIGN KEY (user_system_field_id) REFERENCES SYSTEM_FIELD(id),
   FOREIGN KEY (user_id) REFERENCES GATEWAY_USER(id)
);

